development:
  adapter: async

test:
  adapter: async

production:
    adapter: postgres
  # adapter: redis
  # url: redis://localhost:6379/1
    url: postgres://aexeqdktnpflug:gCCXloKzaiyhN5o_qJ-eLQN98V@ec2-54-243-231-255.compute-1.amazonaws.com:5432/dajdl21g12f2qg
